[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=/usr/bin/x86_64-linux-gnu-gcc"]
ar = "/usr/bin/x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=/usr/bin/aarch64-linux-gnu-gcc"]
ar = "/usr/bin/aarch64-linux-gnu-gcc"
